// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6n8b1c8mnHRPKSSxvQpnWbeP6_RLiEkM',
    appId: '1:873540849087:web:a6c242e6f53679953ae50a',
    messagingSenderId: '873540849087',
    projectId: 'any1space',
    authDomain: 'any1space.firebaseapp.com',
    storageBucket: 'any1space.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnTgvQNF8ZRzjd369xgpa8ctiErMit2c',
    appId: '1:873540849087:android:957e838051998e113ae50a',
    messagingSenderId: '873540849087',
    projectId: 'any1space',
    storageBucket: 'any1space.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7miyp2Ic3TG3p0t8KYWuTggmbAUa7rNs',
    appId: '1:873540849087:ios:d0b9d77da3c5bcd03ae50a',
    messagingSenderId: '873540849087',
    projectId: 'any1space',
    storageBucket: 'any1space.firebasestorage.app',
    iosClientId: '873540849087-s4ilokr4a2m5djs57knm0i33lorftdhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.any1spaceRebuild',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7miyp2Ic3TG3p0t8KYWuTggmbAUa7rNs',
    appId: '1:873540849087:ios:d0b9d77da3c5bcd03ae50a',
    messagingSenderId: '873540849087',
    projectId: 'any1space',
    storageBucket: 'any1space.firebasestorage.app',
    iosClientId: '873540849087-s4ilokr4a2m5djs57knm0i33lorftdhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.any1spaceRebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6n8b1c8mnHRPKSSxvQpnWbeP6_RLiEkM',
    appId: '1:873540849087:web:689d34e52a20f5d23ae50a',
    messagingSenderId: '873540849087',
    projectId: 'any1space',
    authDomain: 'any1space.firebaseapp.com',
    storageBucket: 'any1space.firebasestorage.app',
  );
}

